export const TMDB_READ_ACCESS_TOKEN = process.env.NEXT_PUBLIC_TMDB_READ_ACCESS_TOKEN;
export const TMDB_BASE_URL = process.env.NEXT_PUBLIC_TMDB_API_URL;
export const TMDB_API_KEY = process.env.NEXT_PUBLIC_TMDB_API_KEY;
export const NEXT_PUBLIC_TMDB_IMG_URL= process.env.NEXT_PUBLIC_TMDB_IMG_URL;